# Generated by Django 5.0.4 on 2024-04-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=150)),
                ('measurement', models.CharField(choices=[('c', 'cups'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('oz', 'ounces'), ('fl.oz', 'fluid ounces'), ('lbs', 'pounds')], default='c', max_length=100)),
                ('amount', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appetitApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appetitApp.recipe')),
            ],
        ),
    ]
