# Generated by Django 5.0.4 on 2024-04-21 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0002_remove_directions_recipe_useprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseProfile',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
