# Generated by Django 5.0.4 on 2024-04-22 19:41
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0004_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='measurement',
        ),
    ]
