# Generated by Django 5.0.4 on 2024-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0005_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='directions',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='measurement',
        ),
    ]
