# Generated by Django 5.0.4 on 2024-04-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0005_folder'),
        ('appetitApp', '0005_remove_ingredients_amount_and_more'),
    ]

    operations = [
    ]
