# Generated by Django 5.0.4 on 2024-04-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0006_merge_20240422_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='directions',
        ),
    ]
