# Generated by Django 5.0.4 on 2024-04-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0007_photo_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='folders',
            field=models.ManyToManyField(to='appetitApp.folder'),
        ),
    ]
