# Generated by Django 5.0.4 on 2024-04-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0007_photo_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
