# Generated by Django 5.0.4 on 2024-04-23 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0008_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ccreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
