# Generated by Django 5.0.4 on 2024-04-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0009_review_ccreated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
