# Generated by Django 5.0.4 on 2024-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0009_recipe_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='recipe',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='folders',
            field=models.ManyToManyField(to='appetitApp.folder'),
        ),
    ]
