# Generated by Django 5.0.4 on 2024-04-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0010_rename_ccreated_at_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
