# Generated by Django 5.0.4 on 2024-04-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0008_recipe_folders'),
        ('appetitApp', '0010_remove_review_recipe_userprofile_folders'),
    ]

    operations = [
    ]
