# Generated by Django 5.0.4 on 2024-04-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0013_userprofile_folders_review_delete_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
