# Generated by Django 5.0.4 on 2024-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetitApp', '0016_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
